name : start selenoid 3

on: workflow_dispatch

jobs:
  tests:
    runs-on: ubuntu-latest
    name: selenoid 3 
    steps:
    - name: <e.g. Selenoid >
      uses: ajinx/selenoid@v2
    - uses: actions/checkout@v2
    - run: npm ci  
    - name: <Any test job run name>
      run: <Test execution command e.g. mvn test, npm test etc>
